version: "2"
services:
  db:
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=wad
      - MYSQL_ROOT_PASSWORD=password
  apache:
    image: php:7.0-apache
    volumes:
      - "./:/var/www/html/"
    links:
      - db:db
    ports:
      - "80:80"
      - "443:443"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8080:80"
